default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5433
  username: postgres
  password: postgres


development:
  <<: *default
  database: Authorly_development


test:
  <<: *default
  database: Authorly_test
